// Generated by dts-bundle-generator v9.5.1

export type KrvKeyPart =
  Uint8Array | string | number | bigint | boolean | symbol;
export type KrvKey = readonly KrvKeyPart[];
export type KrvEntry<T, K = KrvKey> = {
  key: K;
  value: T;
  versionstamp: string;
};
export type KrvEntryMaybe<T, K = KrvKey> =
  | KrvEntry<T, K>
  | {
      key: K;
      value: null;
      versionstamp: null;
    };
/**
 * Result of `list` with `values: false`: `await` it for an array of entries,
 * or `for await` over it to stream them. Each use runs a fresh read.
 */
export type KrvListResult<T, K = KrvKey> = AsyncIterable<KrvEntry<T, K>> &
  PromiseLike<KrvEntry<T, K>[]>;
/** Result of `list` (default): the rows only, no key or versionstamp. */
export type KrvValuesResult<T> = AsyncIterable<T> & PromiseLike<T[]>;
export type KrvCommitResult = {
  ok: true;
  versionstamp: string;
};
export type KrvCommitError = {
  ok: false;
};
export type KrvConsistency = "strong" | "eventual";
export type KrvGetOptions = {
  consistency?: KrvConsistency;
};
export type KrvSetOptions<Field extends string = string> = {
  expireIn?: number;
  /**
   * Transformed fields whose values are already stored values (a hash,
   * ciphertext…), written as they are instead of through the transform.
   * Fields with a `load` are loaded first, so they must be readable with the
   * current secrets and are validated as plain values.
   */
  raw?: readonly Field[];
  /**
   * Only write if the key's current versionstamp matches.
   * `null` means "only write if the key doesn't exist yet".
   */
  check?: string | null;
};
export type KrvInsertOptions<Field extends string = string> = {
  expireIn?: number;
  /**
   * Transformed fields whose values are already stored values (a hash,
   * ciphertext…), written as they are instead of through the transform.
   * Fields with a `load` are loaded first, so they must be readable with the
   * current secrets and are validated as plain values.
   */
  raw?: readonly Field[];
};
export type KrvDeleteOptions = {
  /** Only delete if the key's current versionstamp matches. */
  check?: string | null;
  /**
   * Also delete every row that references this one, recursively.
   * Without it, deleting a referenced row throws (restrict).
   */
  cascade?: boolean;
};
export type KrvListOptions<
  Row,
  Where = {
    [K in keyof Row]?: Row[K];
  },
> = {
  /**
   * Equality on top-level fields; nested objects match partially. Values of
   * transformed fields are transformed first, as if written. Key fields,
   * references and indexes narrow what's read; other fields are compared
   * while scanning.
   */
  where?: Where;
  /** Any condition, run on each row (after `where`, before `limit`). */
  filter?: (row: Row) => boolean;
  limit?: number;
  reverse?: boolean;
  consistency?: KrvConsistency;
  /** `false`: return `{ key, value, versionstamp }` entries instead of just the rows. Default `true`. */
  values?: boolean;
};
export type KrvUpdateOptions<Field extends string = string> = {
  /** Only update if the row's current versionstamp matches. */
  check?: string;
  expireIn?: number;
  /**
   * Transformed fields whose values are already stored values (a hash,
   * ciphertext…), written as they are instead of through the transform.
   * Fields with a `load` are loaded first, so they must be readable with the
   * current secrets and are validated as plain values.
   */
  raw?: readonly Field[];
};
type Replaced = Date | Uint8Array | readonly unknown[];
/**
 * A partial row for `update`: nested objects are partial too (merged);
 * arrays and maps are replaced whole. `undefined` removes a field.
 */
export type KrvPatch<T> = {
  [K in keyof T]?: T[K] extends Replaced
    ? T[K] | undefined
    : T[K] extends object
      ? string extends keyof T[K]
        ? T[K] | undefined
        : KrvPatch<T[K]> | undefined
      : T[K] | undefined;
};
/** Runtime shape of an `expand` entry (typed per table by `KrvExpand`). */
export type KrvExpandSpec =
  | string
  | {
      from: string;
      where?: Record<string, unknown>;
      filter?: (row: never) => boolean;
      limit?: number;
      reverse?: boolean;
      expand?: Record<string, KrvExpandSpec>;
    };
/**
 * A value type in a schema:
 * - a type name: `"string"`, `"number"`, `"boolean"`, `"bigint"`, `"date"`,
 *   `"unknown"`, `"id"`, or a custom validator (`"email"`, `"str(3, 50)"`)
 * - a string literal: `"|draft|"`
 * - a key field `"{userId}"` or a reference `"{users.userId}"` (top level only)
 * - a raw literal: `1`, `true`, `null`, `undefined`
 * - a union: `["string", "number"]`
 * - a nested object: `{ street: "string" }`
 */
export type KrvSpec =
  | string
  | number
  | boolean
  | null
  | undefined
  | readonly KrvSpec[]
  | {
      readonly [field: string]: KrvSpec;
    };
/**
 * Fields of a table or nested object. Field names carry modifiers:
 * `"name?"` optional, `"name[]"` array, `"name{}"` map, combined left to
 * right (`"name[]?"`, `"name{}[]"`).
 */
export type KrvSchemaDef = {
  readonly [field: string]: KrvSpec;
};
/** Argument value of a custom validator: `"str(3, |x|, true)"`. */
export type KrvValidatorArg = number | string | boolean | null;
/**
 * A custom validator: a base type, checked first, and a function that gets
 * the already typed value (and the arguments, if declared with any).
 */
export type KrvValidator = readonly [
  base: KrvSpec,
  check: (value: never, args: never) => boolean,
];
export type KrvValidators = Record<string, KrvValidator>;
type Builtins = {
  string: string;
  number: number;
  boolean: boolean;
  bigint: bigint;
  date: Date;
  unknown: unknown;
  id: string;
};
export type KrvBuiltin = keyof Builtins;
/** No custom validators. */
export type KrvNoValidators = Record<never, never>;
type Prettify<T> = {
  [K in keyof T]: T[K];
} & {};
type Trim<S> = S extends ` ${infer R}`
  ? Trim<R>
  : S extends `${infer R} `
    ? Trim<R>
    : S;
type SplitParams<S> = S extends `${infer A},${infer R}`
  ? [Trim<A>, ...SplitParams<R>]
  : Trim<S> extends ""
    ? []
    : [Trim<S>];
type DeclName<K> = K extends `${infer N}(${string})` ? N : K;
type DeclParams<K> = K extends `${string}(${infer P})` ? SplitParams<P> : [];
type FindValidator<Name, F> = {
  [K in keyof F]: DeclName<K> extends Name ? K : never;
}[keyof F];
type BaseOf<V> = V extends readonly [infer Base, unknown] ? Base : never;
type ArgsOf<V> = V extends readonly [
  unknown,
  (value: never, args: infer A) => boolean,
]
  ? A
  : never;
type StringSpecType<S extends string, F> = S extends KrvBuiltin
  ? Builtins[S]
  : S extends `|${infer L}|`
    ? L
    : S extends `{${string}}`
      ? string
      : S extends `${infer N}(${string})`
        ? ValidatorType<FindValidator<N, F>, F>
        : ValidatorType<FindValidator<S, F>, F>;
type ValidatorType<K, F> = [K] extends [never]
  ? never
  : K extends keyof F
    ? KrvSpecType<BaseOf<F[K]>, KrvNoValidators>
    : never;
/** TypeScript type of a value spec. `F` holds the custom validators. */
export type KrvSpecType<S, F> = S extends string
  ? StringSpecType<S, F>
  : S extends readonly (infer E)[]
    ? KrvSpecType<E, F>
    : S extends number | boolean | null | undefined
      ? S
      : S extends object
        ? KrvObjectType<S, F>
        : never;
/** `"tags[]?"` → `"tags"` */
export type KrvFieldName<K> = K extends `${infer R}?`
  ? KrvFieldName<R>
  : K extends `${infer R}[]`
    ? KrvFieldName<R>
    : K extends `${infer R}{}`
      ? KrvFieldName<R>
      : K;
type Wrap<K, T> = K extends `${infer R}?`
  ? Wrap<R, T>
  : K extends `${infer R}[]`
    ? Wrap<R, T>[]
    : K extends `${infer R}{}`
      ? Record<string, Wrap<R, T>>
      : T;
type IsOptional<K, S, F> = K extends `${string}?`
  ? true
  : undefined extends KrvSpecType<S, F>
    ? true
    : false;
type IsGenerated<K, S> =
  K extends KrvFieldName<K>
    ? S extends "id"
      ? true
      : S extends `{${string}.${string}}`
        ? false
        : S extends `{${string}}`
          ? true
          : false
    : false;
type Field<K, S, F> = Wrap<K, KrvSpecType<S, F>>;
export type KrvObjectType<S, F> = Prettify<
  {
    -readonly [
      K in keyof S as IsOptional<K, S[K], F> extends true
        ? never
        : KrvFieldName<K>
    ]-?: Field<K, S[K], F>;
  } & {
    -readonly [
      K in keyof S as IsOptional<K, S[K], F> extends true
        ? KrvFieldName<K>
        : never
    ]?: Field<K, S[K], F>;
  }
>;
/** What `insert`/`set` accept: generated fields may be left out. */
export type KrvInputType<S, F> = Prettify<
  {
    -readonly [
      K in keyof S as IsOptional<K, S[K], F> extends true
        ? never
        : IsGenerated<K, S[K]> extends true
          ? never
          : KrvFieldName<K>
    ]-?: Field<K, S[K], F>;
  } & {
    -readonly [
      K in keyof S as IsOptional<K, S[K], F> extends true
        ? KrvFieldName<K>
        : IsGenerated<K, S[K]> extends true
          ? KrvFieldName<K>
          : never
    ]?: Field<K, S[K], F>;
  }
>;
type ArgTemplate<T> = [T] extends [never]
  ? AnyArgTemplate
  : unknown extends T
    ? AnyArgTemplate
    : | (T extends number ? `${number}` : never)
      | (T extends string ? `|${string}|` : never)
      | (T extends boolean ? `${T}` : never)
      | (T extends null ? "null" : never);
type AnyArgTemplate = `${number}` | `|${string}|` | "true" | "false" | "null";
type JoinArgs<Params, Args> = Params extends [infer P, ...infer Rest]
  ? Rest extends []
    ? ArgTemplate<P extends keyof Args ? Args[P] : never>
    : `${ArgTemplate<P extends keyof Args ? Args[P] : never>}, ${JoinArgs<Rest, Args>}`
  : "";
type ValidatorUsage<F> = {
  [K in keyof F & string]: DeclParams<K> extends []
    ? K
    : `${DeclName<K>}(${JoinArgs<DeclParams<K>, ArgsOf<F[K]>>})`;
}[keyof F & string];
type ValidString<F> =
  KrvBuiltin | `|${string}|` | `{${string}}` | ValidatorUsage<F>;
/** A value spec where every type name exists and every call is well-formed. */
export type KrvSpecFor<F> =
  | ValidString<F>
  | number
  | boolean
  | null
  | undefined
  | readonly KrvSpecFor<F>[]
  | {
      readonly [field: string]: KrvSpecFor<F>;
    };
export type KrvSchemaFor<F> = {
  readonly [field: string]: KrvSpecFor<F>;
};
/**
 * The declaration shape `openKRV` expects for `validators`: the function's
 * value parameter is typed from the base.
 */
export type KrvValidatorDefs<V> = {
  [K in keyof V]: readonly [
    V[K],
    (value: KrvSpecType<V[K], KrvNoValidators>, args: never) => boolean,
  ];
};
/**
 * What a transform character does with a field (declared in `openKRV`):
 * - `save`: the value to store instead of the plain one (can be async).
 * - `load`: restores the plain value on read. Without it, reads return what
 *   was stored (e.g. a hash).
 * - `compare`: checks a plain value against the stored one (`db.compare`).
 * - `deterministic`: the same input always gives the same output, so the
 *   field can be searched with `where` and indexed.
 */
export type KrvTransform = {
  save: (value: any) => unknown;
  load?: (stored: any) => unknown;
  compare?: (plain: any, stored: any) => boolean | Promise<boolean>;
  deterministic?: boolean;
};
export type KrvTransforms = Record<string, KrvTransform>;
/** No transforms. */
export type KrvNoTransforms = Record<never, never>;
type Chars<T> = keyof T & string;
type StripOptional<K> = K extends `${infer R}?` ? R : K;
type CharOf<K, T> = {
  [C in Chars<T>]: StripOptional<K> extends `${string}${C}` ? C : never;
}[Chars<T>];
type StripTransform<K, T> = [CharOf<K, T>] extends [never]
  ? StripOptional<K>
  : StripOptional<K> extends `${infer R}${CharOf<K, T>}`
    ? R
    : StripOptional<K>;
/** Name of a table's top-level field: `"tokens[]&?"` → `"tokens"`. */
export type KrvTopFieldName<K, T> = KrvFieldName<StripTransform<K, T>>;
type ItemOutput<K, S, V, T> = [CharOf<K, T>] extends [never]
  ? KrvSpecType<S, V>
  : T[CharOf<K, T> & keyof T] extends {
        load: (stored: never) => unknown;
      }
    ? KrvSpecType<S, V>
    : string;
type TopField<K, S, V, T> = Wrap<StripTransform<K, T>, ItemOutput<K, S, V, T>>;
type TopFieldInput<K, S, V, T> = Wrap<StripTransform<K, T>, KrvSpecType<S, V>>;
type Timestamps<TS> = TS extends false
  ? KrvNoTransforms
  : {
      createdAt: number;
      updatedAt: number;
    };
/** A table row as read back. `V`: validators, `T`: transforms, `TS`: timestamps. */
export type KrvTableRow<S, V, T, TS> = Prettify<
  {
    -readonly [
      K in keyof S as IsOptional<K, S[K], V> extends true
        ? never
        : KrvTopFieldName<K, T>
    ]-?: TopField<K, S[K], V, T>;
  } & {
    -readonly [
      K in keyof S as IsOptional<K, S[K], V> extends true
        ? KrvTopFieldName<K, T>
        : never
    ]?: TopField<K, S[K], V, T>;
  } & Timestamps<TS>
>;
/** What `insert`/`set` accept: plain values; generated fields and timestamps may be left out. */
export type KrvTableInput<S, V, T, TS> = Prettify<
  {
    -readonly [
      K in keyof S as IsOptional<K, S[K], V> extends true
        ? never
        : IsGenerated<K, S[K]> extends true
          ? never
          : KrvTopFieldName<K, T>
    ]-?: TopFieldInput<K, S[K], V, T>;
  } & {
    -readonly [
      K in keyof S as IsOptional<K, S[K], V> extends true
        ? KrvTopFieldName<K, T>
        : IsGenerated<K, S[K]> extends true
          ? KrvTopFieldName<K, T>
          : never
    ]?: TopFieldInput<K, S[K], V, T>;
  } & Partial<Timestamps<TS>>
>;
type WhereValue<X> = X extends Date | Uint8Array | readonly unknown[]
  ? X
  : X extends object
    ? {
        [K in keyof X]?: WhereValue<X[K]>;
      }
    : X;
type Searchable<K, T, Using> = [CharOf<K, T>] extends [never]
  ? true
  : T[CharOf<K, T> & keyof T] extends {
        deterministic: true;
      }
    ? true
    : KrvTopFieldName<K, T> extends Using
      ? true
      : false;
/** `where` of a table: equality on plain values, nested objects match partially. */
export type KrvTableWhere<S, V, T, TS, Using = never> = Prettify<
  {
    -readonly [
      K in keyof S as Searchable<K, T, Using> extends true
        ? KrvTopFieldName<K, T>
        : never
    ]?: WhereValue<TopFieldInput<K, S[K], V, T>>;
  } & Partial<Timestamps<TS>>
>;
/** A secondary index over top-level fields. */
export type KrvIndex = {
  fields: readonly string[];
  /** Two rows can't share the same values: the second write throws `KrvConflictError`. */
  unique?: boolean;
  /**
   * A deterministic transform applied to the plain value before indexing, so
   * `where` can search a field stored encrypted (a blind index): `"#"` for
   * every field, or `{ phone: "#" }` per field.
   */
  using?: string | Readonly<Record<string, string>>;
};
export type KrvIndexes = Readonly<Record<string, KrvIndex>>;
export type KrvTable<
  Key extends readonly string[] = readonly string[],
  Schema extends KrvSchemaDef = KrvSchemaDef,
  Timestamps extends boolean = boolean,
  Indexes extends KrvIndexes = KrvIndexes,
> = {
  /** Key pattern: literal parts, and `{placeholder}` parts filled from the row. */
  readonly key: Key;
  readonly schema: Schema;
  /** Automatic `createdAt` / `updatedAt` fields. Default `true`. */
  readonly timestamps?: Timestamps;
  readonly indexes?: Indexes;
};
/** A database's tables: a list, each named by its key's literal parts. */
export type KrvTables = readonly KrvTable[];
/** Validators and transforms, as seen by the row types. */
export type KrvEnv<V = KrvNoValidators, T = KrvNoTransforms> = {
  v: V;
  t: T;
};
type AnyTable<Key extends readonly string[] = any, Schema = any, TS = any> = {
  readonly key: Key;
  readonly schema: Schema;
  readonly timestamps?: TS;
};
type TimestampsOf<Table> = Table extends {
  readonly timestamps?: infer TS;
}
  ? boolean extends TS
    ? true
    : TS extends false
      ? false
      : true
  : true;
type EnvV<E> = E extends {
  v: infer V;
}
  ? V
  : KrvNoValidators;
type EnvT<E> = E extends {
  t: infer T;
}
  ? T
  : KrvNoTransforms;
/** Row type of a table, as read back. */
export type KrvTableValue<Table, E = KrvEnv> =
  Table extends AnyTable<readonly string[], infer Schema>
    ? KrvTableRow<Schema, EnvV<E>, EnvT<E>, TimestampsOf<Table>>
    : never;
/** What `insert`/`set` accept for a table. */
export type KrvTableInputValue<Table, E = KrvEnv> =
  Table extends AnyTable<readonly string[], infer Schema>
    ? KrvTableInput<Schema, EnvV<E>, EnvT<E>, TimestampsOf<Table>>
    : never;
type UsingFields<Table> = Table extends {
  readonly indexes?: infer I;
}
  ? {
      [N in keyof I]: I[N] extends {
        using: string;
        fields: readonly (infer F)[];
      }
        ? F
        : I[N] extends {
              using: infer U;
            }
          ? keyof U
          : never;
    }[keyof I]
  : never;
/** `where` of a table. */
export type KrvTableWhereValue<Table, E = KrvEnv> =
  Table extends AnyTable<readonly string[], infer Schema>
    ? KrvTableWhere<
        Schema,
        EnvV<E>,
        EnvT<E>,
        TimestampsOf<Table>,
        UsingFields<Table> & string
      >
    : never;
type KeyPartType<Part> = Part extends `{${string}}` ? string : Part;
/** Row key of a table: `["users", "{userId}"]` → `readonly ["users", string]`. */
export type KrvRowKey<Table> =
  Table extends AnyTable<infer Key>
    ? {
        readonly [I in keyof Key]: KeyPartType<Key[I]>;
      }
    : never;
type Literals<Key> = Key extends readonly [infer Head, ...infer Rest]
  ? Head extends `{${string}}`
    ? Literals<Rest>
    : [Head, ...Literals<Rest>]
  : [];
/** Literal parts of a table's key, used by `insert` and `list`: `["posts"]`. */
export type KrvTableLiterals<Table> =
  Table extends AnyTable<infer Key> ? Readonly<Literals<Key>> : never;
export type KrvAnyKey<Tables extends KrvTables> = KrvRowKey<Tables[number]>;
export type KrvAnyLiterals<Tables extends KrvTables> = KrvTableLiterals<
  Tables[number]
>;
type TableAtKeyOf<Table, Key> = Table extends unknown
  ? Key extends KrvRowKey<Table>
    ? Table
    : never
  : never;
export type KrvTableAtKey<Tables extends KrvTables, Key> = TableAtKeyOf<
  Tables[number],
  Key
>;
type TableAtLiteralsOf<Table, Literals> = Table extends unknown
  ? [Literals] extends [KrvTableLiterals<Table>]
    ? [KrvTableLiterals<Table>] extends [Literals]
      ? Table
      : never
    : never
  : never;
export type KrvTableAtLiterals<
  Tables extends KrvTables,
  Literals,
> = TableAtLiteralsOf<Tables[number], Literals>;
export type KrvValueAt<Tables extends KrvTables, E, Key> = KrvTableValue<
  KrvTableAtKey<Tables, Key>,
  E
>;
export type KrvInputAt<Tables extends KrvTables, E, Key> = KrvTableInputValue<
  KrvTableAtKey<Tables, Key>,
  E
>;
export type KrvValueAtLiterals<
  Tables extends KrvTables,
  E,
  Literals,
> = KrvTableValue<KrvTableAtLiterals<Tables, Literals>, E>;
export type KrvInputAtLiterals<
  Tables extends KrvTables,
  E,
  Literals,
> = KrvTableInputValue<KrvTableAtLiterals<Tables, Literals>, E>;
export type KrvWhereAtLiterals<
  Tables extends KrvTables,
  E,
  Literals,
> = KrvTableWhereValue<KrvTableAtLiterals<Tables, Literals>, E>;
export type KrvRowKeyAtLiterals<Tables extends KrvTables, Literals> = KrvRowKey<
  KrvTableAtLiterals<Tables, Literals>
>;
/** Top-level field names of the table at a key, for `db.compare`. */
export type KrvFieldAt<Tables extends KrvTables, E, Key> = keyof KrvValueAt<
  Tables,
  E,
  Key
> &
  string;
/**
 * The database API with loosely typed rows: what a migration's `db` is when
 * `KrvMigration` isn't given your database's type.
 */
export type KrvUntypedDb = {
  get(key: KrvKey, options?: KrvGetOptions): Promise<KrvEntryMaybe<any>>;
  set(
    key: KrvKey,
    value: any,
    options?: KrvSetOptions,
  ): Promise<KrvCommitResult>;
  insert(
    literals: KrvKey,
    value: any,
    options?: KrvInsertOptions,
  ): Promise<
    KrvCommitResult & {
      key: KrvKey;
      value: any;
    }
  >;
  update(key: KrvKey, patch: any, options?: KrvUpdateOptions): Promise<any>;
  delete(key: KrvKey, options?: KrvDeleteOptions): Promise<void>;
  list(
    literals: KrvKey,
    options?: KrvListOptions<any, any>,
  ): KrvListResult<any>;
  find(
    literals: KrvKey,
    options?: Omit<KrvListOptions<any, any>, "limit">,
  ): Promise<any | null>;
  compare(key: KrvKey, field: string, plain: unknown): Promise<boolean>;
};
/**
 * The database inside a migration's `up`: `Db` (your database's type, or
 * loosely typed rows by default), plus raw access and the transforms.
 */
export type KrvMigrationDb<Db = KrvUntypedDb> = Omit<
  Db,
  "raw" | "transforms" | "close"
> & {
  /**
   * The underlying `Deno.Kv`: no schemas, validation, transforms, indexes or
   * timestamps. Use it to read and rewrite data in an old shape. Indexes of
   * every table are rebuilt after the migrations.
   */
  raw: Deno.Kv;
  /**
   * Your transforms, by character, e.g. `db.transforms["&"].save(value)`.
   * `db.raw` skips them, so call them yourself when writing raw data.
   */
  transforms: KrvTransforms;
};
/**
 * A migration: the default export of a file named
 * `YYYY-MM-DD--NNN[--name].ts`. The file name is its identity: migrations run
 * by date, then by number.
 *
 * @example
 * ```ts
 * // migrations/2026-09-24--001--add-age.ts
 * export default {
 *   url: import.meta.url,
 *   up: async (db) => { … },
 * } satisfies KrvMigration;
 * ```
 */
export type KrvMigration<Db = KrvUntypedDb> = {
  /**
   * `import.meta.url`: where the file name is read from. Only the name is
   * kept, not the path.
   */
  url: string;
  description?: string;
  /** `false`: skipped and not recorded, so it runs once enabled. Default `true`. */
  enabled?: boolean;
  up: (db: KrvMigrationDb<Db>) => unknown;
};
type AnyMigration = Omit<KrvMigration, "up"> & {
  up: (db: never) => unknown;
};
/** A migration, or a module exporting one as default (`import("./m.ts")`). */
export type KrvMigrationSource =
  | AnyMigration
  | {
      default: AnyMigration;
    }
  | Promise<
      | AnyMigration
      | {
          default: AnyMigration;
        }
    >;
/** A migration as loaded, with what its file name says. */
export type KrvLoadedMigration = AnyMigration & {
  /**
   * `YYYY-MM-DD--NNN`: what's recorded once applied, so renaming the name
   * part of the file doesn't run it again.
   */
  id: string;
  /** The file name without extension, e.g. `2026-09-24--001--users`. */
  fileName: string;
  /** The optional name part, e.g. `users`. */
  name?: string;
};
/** Applied migrations, stored in `["__krv", "migrations", id]`. Only the name, never the path. */
export type KrvAppliedMigration = {
  id: string;
  fileName: string;
  description?: string;
  appliedAt: number;
  durationMs: number;
};
/** Migration lifecycle hooks. Each is awaited; a throw fails the migrations. */
export type KrvEvents = {
  /** After the backup exists, before the first pending migration runs. */
  beforeMigrations?: (event: {
    pending: KrvLoadedMigration[];
    backupPath: string | null;
  }) => unknown;
  beforeMigration?: (event: { migration: KrvLoadedMigration }) => unknown;
  afterMigration?: (event: {
    migration: KrvLoadedMigration;
    durationMs: number;
  }) => unknown;
  /** After the backup has been restored. `migration` is null if the failure came later (checks). */
  migrationFailed?: (event: {
    migration: KrvLoadedMigration | null;
    error: unknown;
    backupPath: string | null;
  }) => unknown;
  afterMigrations?: (event: { applied: KrvLoadedMigration[] }) => unknown;
};
type SplitDot<S extends string> = S extends `${infer H}.${infer R}`
  ? [H, ...SplitDot<R>]
  : [S];
type JoinDot<T> = T extends [infer H extends string]
  ? H
  : T extends [infer H extends string, ...infer R]
    ? `${H}.${JoinDot<R>}`
    : "";
type InitOf<T> = T extends [...infer I, unknown] ? I : [];
/** A table's name: its key's literal parts, joined by dots. */
export type KrvTableName<Table> =
  KrvTableLiterals<Table> extends readonly [...infer L] ? JoinDot<L> : never;
type TableByName<Tables extends KrvTables, Name> = TableByNameOf<
  Tables[number],
  Name
>;
type TableByNameOf<Table, Name> = Table extends unknown
  ? KrvTableName<Table> extends Name
    ? Table
    : never
  : never;
type SchemaOf<Table> = Table extends {
  readonly schema: infer S;
}
  ? S
  : never;
type KeyOf<Table> = Table extends {
  readonly key: infer K;
}
  ? K
  : never;
type RefString<V> = V extends `{${infer R}}`
  ? R extends `${string}.${string}`
    ? R
    : never
  : V extends readonly (infer U)[]
    ? RefString<U>
    : never;
type RefFields<Table> = {
  [
    K in keyof SchemaOf<Table> as [RefString<SchemaOf<Table>[K]>] extends [
      never,
    ]
      ? never
      : KrvFieldName<K>
  ]: RefString<SchemaOf<Table>[K]>;
};
type TargetName<Ref> = Ref extends string
  ? JoinDot<InitOf<SplitDot<Ref>>>
  : never;
type Placeholders<Key> = Key extends readonly (infer P)[]
  ? P extends `{${infer Name}}`
    ? Name
    : never
  : never;
type ReverseRefs<Tables extends KrvTables, Table> = ReverseRefsOf<
  Tables[number],
  Table
>;
type ReverseRefsOf<Source, Table> = Source extends unknown
  ? {
      [F in keyof RefFields<Source>]: TargetName<
        RefFields<Source>[F]
      > extends KrvTableName<Table>
        ? `${KrvTableName<Source>}.${F & string}`
        : never;
    }[keyof RefFields<Source>]
  : never;
type ForwardRefs<Table> = keyof RefFields<Table> & string;
type Depth = unknown[];
type Next<D extends Depth> = [...D, unknown];
type ForwardEntry<
  Tables extends KrvTables,
  E,
  Table,
  F,
  D extends Depth,
> = F extends string
  ? {
      /** A reference field of this row: expands to the row it points to. */
      from: F;
      expand?: KrvExpand<
        Tables,
        E,
        TableByName<
          Tables,
          TargetName<RefFields<Table>[F & keyof RefFields<Table>]>
        >,
        Next<D>
      >;
    }
  : never;
type ReverseEntry<
  Tables extends KrvTables,
  E,
  R,
  D extends Depth,
> = R extends string
  ? ReverseEntryOf<
      Tables,
      E,
      R,
      TableByName<Tables, JoinDot<InitOf<SplitDot<R>>>>,
      D
    >
  : never;
type ReverseEntryOf<Tables extends KrvTables, E, R, Source, D extends Depth> = {
  /** `"<table>.<field>"` referencing this row: expands to those rows. */
  from: R;
  where?: KrvTableWhereValue<Source, E>;
  filter?: (row: KrvTableValue<Source, E>) => boolean;
  limit?: number;
  reverse?: boolean;
  expand?: KrvExpand<Tables, E, Source, Next<D>>;
};
type ExpandEntry<Tables extends KrvTables, E, Table, D extends Depth> =
  | ForwardRefs<Table>
  | ReverseRefs<Tables, Table>
  | ForwardEntry<Tables, E, Table, ForwardRefs<Table>, D>
  | ReverseEntry<Tables, E, ReverseRefs<Tables, Table>, D>;
/**
 * `expand` of a table: property name → what to expand into it. A field of
 * this row (`"authorId"`) gives one row; another table's field referencing
 * this one (`"books.authorId"`) gives a list. Names can't clash with fields.
 */
export type KrvExpand<
  Tables extends KrvTables,
  E,
  Table,
  D extends Depth = [],
> = D["length"] extends 4
  ? never
  : Record<string, ExpandEntry<Tables, E, Table, D>>;
type FromOf<X> = X extends string
  ? X
  : X extends {
        from: infer F;
      }
    ? F
    : never;
type NestedOf<X> = X extends {
  expand: infer N;
}
  ? N
  : Record<never, never>;
type ForwardResult<Tables extends KrvTables, E, Table, X> =
  TableByName<
    Tables,
    TargetName<RefFields<Table>[FromOf<X> & keyof RefFields<Table>]>
  > extends infer Target
    ? | KrvExpanded<Tables, E, Target, KrvTableValue<Target, E>, NestedOf<X>>
      | (null extends KrvTableValue<Table, E>[FromOf<X> &
          keyof KrvTableValue<Table, E>]
          ? null
          : undefined extends KrvTableValue<Table, E>[FromOf<X> &
                keyof KrvTableValue<Table, E>]
            ? null
            : never)
    : never;
type ReverseResult<Tables extends KrvTables, E, Table, X> =
  TableByName<
    Tables,
    JoinDot<InitOf<SplitDot<FromOf<X> & string>>>
  > extends infer Source
    ? KrvExpanded<
        Tables,
        E,
        Source,
        KrvTableValue<Source, E>,
        NestedOf<X>
      > extends infer Row
      ? [Placeholders<KeyOf<Source>>] extends [Placeholders<KeyOf<Table>>]
        ? Row | null
        : Row[]
      : never
    : never;
type ExpandResult<Tables extends KrvTables, E, Table, X> =
  FromOf<X> extends `${string}.${string}`
    ? ReverseResult<Tables, E, Table, X>
    : ForwardResult<Tables, E, Table, X>;
type Prettify$1<T> = {
  [K in keyof T]: T[K];
} & {};
/** Expanded names that clash with a field of the table: each one is an error. */
export type KrvExpandNoClash<X, Table, E> = {
  [K in Extract<keyof X, keyof KrvTableValue<Table, E>>]: never;
};
/** A row with its `expand`ed properties. */
export type KrvExpanded<Tables extends KrvTables, E, Table, Row, X> = [
  keyof X,
] extends [never]
  ? Row
  : Prettify$1<
      Row & {
        -readonly [N in keyof X]: ExpandResult<Tables, E, Table, X[N]>;
      }
    >;
/**
 * The typed read/write API returned by `openKRV`. `Tables` and `E`
 * (validators and transforms) drive the row types.
 *
 * `in out` skips variance measurement, which is too deep for these types.
 */
export interface KrvDatabase<in out Tables extends KrvTables, in out E> {
  /**
   * Reads one row by its full key.
   *
   * @param key Full row key, e.g. `["users", id]`, or `["config"]` for a
   *   static table.
   * @param options `consistency`: `"strong"` (default) or `"eventual"`.
   * @returns The entry, with transforms loaded. `value` and `versionstamp`
   *   are `null` when the row doesn't exist.
   * @throws Error if the key doesn't belong to any table.
   *
   * @example
   * ```ts
   * const user = await db.get(["users", id]);
   * if (user.value) console.log(user.value.name, user.value.createdAt);
   * ```
   */
  get: <
    const Key extends KrvAnyKey<Tables>,
    const X extends Record<string, unknown> = Record<never, never>,
  >(
    key: Key,
    options?: KrvGetOptions & {
      expand?: X &
        KrvExpand<Tables, E, KrvTableAtKey<Tables, Key>> &
        NoInfer<KrvExpandNoClash<X, KrvTableAtKey<Tables, Key>, E>>;
    },
  ) => Promise<
    KrvEntryMaybe<
      KrvExpanded<
        Tables,
        E,
        KrvTableAtKey<Tables, Key>,
        KrvValueAt<Tables, E, Key>,
        X
      >,
      Key
    >
  >;
  /**
   * Creates or overwrites a row, in one atomic commit together with its
   * indexes and references.
   *
   * - Key fields left out of `value` are taken from `key`.
   * - `"id"` fields left out keep their current value, or get a new ULID.
   * - `createdAt` keeps its current value; `updatedAt` becomes now. Pass
   *   other values to override them.
   * - Transformed fields are validated as plain values, then saved. Opaque
   *   ones (no `load`, e.g. hashes) passed back unchanged are kept as stored.
   * - If `value` changes a key field, the row **moves** to its new key and
   *   every row referencing it is updated to follow (recursively).
   *
   * @param key Full row key, e.g. `["users", id]`.
   * @param value The row. Validated against the table's schema.
   * @param options
   *   - `check`: only write if the row's current versionstamp matches
   *     (`null`: only if it doesn't exist yet).
   *   - `expireIn`: milliseconds until the row expires.
   *   - `raw`: transformed fields whose values are already stored (a hash,
   *     ciphertext…), written as they are instead of transformed again.
   * @returns `{ ok: true, versionstamp }`.
   * @throws KrvValidationError if `value` doesn't match the schema.
   * @throws KrvConflictError if `check` fails, a unique index value or the
   *   destination of a move is taken, or concurrent writes keep winning.
   * @throws KrvReferenceError if a reference points at a missing row.
   *
   * @example
   * ```ts
   * await db.set(["users", id], { name: "Pablo" });
   *
   * // Optimistic concurrency: read, modify, write only if unchanged.
   * const current = await db.get(["users", id]);
   * await db.set(["users", id], { ...current.value!, age: 30 }, {
   *   check: current.versionstamp,
   * });
   * ```
   */
  set: <const Key extends KrvAnyKey<Tables>>(
    key: Key,
    value: KrvInputAt<Tables, E, Key>,
    options?: KrvSetOptions<KrvFieldAt<Tables, E, Key>>,
  ) => Promise<KrvCommitResult>;
  /**
   * Updates part of a row, without reading it first. The patch is merged into
   * the stored row and written in one atomic commit; if another write lands
   * in between, it's merged again on top of that one.
   *
   * - Nested objects merge; arrays and maps (`[]`, `{}`) are replaced whole.
   * - `undefined` removes a field.
   * - A function receives the current row and returns the patch, for updates
   *   based on the current value (it may run more than once).
   * - Everything `set` does applies: validation of the whole row, transforms,
   *   indexes, references, `updatedAt`, and moves when a key field changes.
   *
   * @param key Full row key.
   * @param patch A partial row, or `(row) => partial row`.
   * @param options
   *   - `check`: only update if the row's current versionstamp matches.
   *   - `expireIn`: milliseconds until the row expires.
   *   - `raw`: transformed fields whose values are already stored (a hash,
   *     ciphertext…), written as they are instead of transformed again.
   * @returns The updated row.
   * @throws KrvNotFoundError if the row doesn't exist.
   * @throws KrvValidationError, KrvConflictError, KrvReferenceError as `set`.
   *
   * @example
   * ```ts
   * await db.update(["notes", id], { done: true });
   * await db.update(["posts", id], (post) => ({ views: post.views + 1 }));
   * ```
   */
  update: <const Key extends KrvAnyKey<Tables>>(
    key: Key,
    patch:
      | KrvPatch<KrvInputAt<Tables, E, Key>>
      | ((
          row: KrvValueAt<Tables, E, Key>,
        ) => KrvPatch<KrvInputAt<Tables, E, Key>>),
    options?: KrvUpdateOptions<KrvFieldAt<Tables, E, Key>>,
  ) => Promise<KrvValueAt<Tables, E, Key>>;
  /**
   * Creates a new row. Key fields and `"id"` fields left out of `value` get a
   * new ULID (time-ordered, so rows list in insertion order).
   *
   * @param literals The table's literal key parts: `["posts"]` for
   *   `["posts", "{postId}"]`, `["orgs", "members"]` for
   *   `["orgs", "{orgId}", "members", "{memberId}"]`.
   * @param value The row. Validated against the table's schema.
   * @param options
   *   - `expireIn`: milliseconds until the row expires.
   *   - `raw`: transformed fields whose values are already stored (a hash,
   *     ciphertext…), written as they are instead of transformed again.
   * @returns The commit result, plus the row's `key` and `value` (including
   *   generated fields and timestamps).
   * @throws KrvValidationError if `value` doesn't match the schema.
   * @throws KrvConflictError if the key or a unique index value is taken.
   * @throws KrvReferenceError if a reference points at a missing row.
   *
   * @example
   * ```ts
   * const user = await db.insert(["users"], { name: "Pablo" });
   * user.key;      // ["users", "01J…"]
   * user.value.id; // "01J…"
   * ```
   */
  insert: <const Literals extends KrvAnyLiterals<Tables>>(
    literals: Literals,
    value: KrvInputAtLiterals<Tables, E, Literals>,
    options?: KrvInsertOptions<
      keyof KrvValueAtLiterals<Tables, E, Literals> & string
    >,
  ) => Promise<
    KrvCommitResult & {
      key: KrvRowKeyAtLiterals<Tables, Literals>;
      value: KrvValueAtLiterals<Tables, E, Literals>;
    }
  >;
  /**
   * Deletes a row, in one atomic commit together with its indexes. Deleting a
   * row that doesn't exist does nothing.
   *
   * @param key Full row key.
   * @param options
   *   - `cascade`: also delete every row referencing this one, recursively.
   *     Without it, deleting a referenced row throws.
   *   - `check`: only delete if the row's current versionstamp matches.
   * @throws KrvReferenceError if the row is referenced and `cascade` is not set.
   * @throws KrvConflictError if `check` fails.
   *
   * @example
   * ```ts
   * await db.delete(["posts", postId]);
   * await db.delete(["users", userId], { cascade: true }); // and their posts
   * ```
   */
  delete: <const Key extends KrvAnyKey<Tables>>(
    key: Key,
    options?: KrvDeleteOptions,
  ) => Promise<void>;
  /**
   * Lists a table's rows, in key order.
   *
   * The result can be awaited for an array of rows, or iterated with
   * `for await` to stream them. Each use reads again.
   *
   * @param literals The table's literal key parts, as for `insert`.
   * @param options
   *   - `where`: equality on top-level fields; nested objects match
   *     partially. Transformed fields are compared by their saved value (only
   *     deterministic transforms). Key fields, unique and secondary indexes
   *     and references narrow what's read; other fields are compared while
   *     scanning.
   *   - `filter`: any condition on the (loaded) row, after `where`.
   *   - `limit`: maximum number of rows, counted after `where` and `filter`.
   *   - `reverse`: reverse key order (newest first for ULID keys).
   *   - `consistency`: `"strong"` (default) or `"eventual"`.
   *   - `values`: `false` to get `{ key, value, versionstamp }` entries
   *     instead of just the rows (default `true`).
   * @throws Error right away (not while iterating) for an unknown table, or a
   *   `where` on a field whose transform isn't deterministic.
   *
   * @example
   * ```ts
   * const posts = await db.list(["posts"], { where: { authorId }, limit: 10 });
   * posts[0].title;
   *
   * for await (const post of db.list(["posts"])) console.log(post.title);
   *
   * const [entry] = await db.list(["posts"], { values: false });
   * entry.key; // ["posts", "01J…"]
   * ```
   */
  list: <
    const Literals extends KrvAnyLiterals<Tables>,
    const Values extends boolean = true,
    const X extends Record<string, unknown> = Record<never, never>,
  >(
    literals: Literals,
    options?: KrvListOptions<
      KrvValueAtLiterals<Tables, E, Literals>,
      KrvWhereAtLiterals<Tables, E, Literals>
    > & {
      values?: Values;
      expand?: X &
        KrvExpand<Tables, E, KrvTableAtLiterals<Tables, Literals>> &
        NoInfer<KrvExpandNoClash<X, KrvTableAtLiterals<Tables, Literals>, E>>;
    },
  ) => Values extends false
    ? KrvListResult<
        KrvExpanded<
          Tables,
          E,
          KrvTableAtLiterals<Tables, Literals>,
          KrvValueAtLiterals<Tables, E, Literals>,
          X
        >,
        KrvRowKeyAtLiterals<Tables, Literals>
      >
    : KrvValuesResult<
        KrvExpanded<
          Tables,
          E,
          KrvTableAtLiterals<Tables, Literals>,
          KrvValueAtLiterals<Tables, E, Literals>,
          X
        >
      >;
  /**
   * Finds the first row matching `where` and `filter`, in key order, or
   * `null`. Same options as `list` (without `limit`), and uses the same
   * indexes.
   *
   * @param literals The table's literal key parts, as for `insert`.
   * @param options `where`, `filter`, `reverse`, `consistency`, and
   *   `values: false` to get `{ key, value, versionstamp }` instead of the row.
   * @throws Error (rejects) for an unknown table, or a `where` on a field that
   *   can't be searched.
   *
   * @example
   * ```ts
   * const user = await db.find(["users"], { where: { email } });
   * if (user) console.log(user.name);
   * ```
   */
  find: <
    const Literals extends KrvAnyLiterals<Tables>,
    const Values extends boolean = true,
    const X extends Record<string, unknown> = Record<never, never>,
  >(
    literals: Literals,
    options?: Omit<
      KrvListOptions<
        KrvValueAtLiterals<Tables, E, Literals>,
        KrvWhereAtLiterals<Tables, E, Literals>
      >,
      "limit"
    > & {
      values?: Values;
      expand?: X &
        KrvExpand<Tables, E, KrvTableAtLiterals<Tables, Literals>> &
        NoInfer<KrvExpandNoClash<X, KrvTableAtLiterals<Tables, Literals>, E>>;
    },
  ) => Promise<
    | (Values extends false
        ? KrvEntry<
            KrvExpanded<
              Tables,
              E,
              KrvTableAtLiterals<Tables, Literals>,
              KrvValueAtLiterals<Tables, E, Literals>,
              X
            >,
            KrvRowKeyAtLiterals<Tables, Literals>
          >
        : KrvExpanded<
            Tables,
            E,
            KrvTableAtLiterals<Tables, Literals>,
            KrvValueAtLiterals<Tables, E, Literals>,
            X
          >)
    | null
  >;
  /**
   * Checks a plain value against a transformed field's stored value, e.g. a
   * password against its bcrypt hash. Uses the transform's `compare`; without
   * one, a deterministic transform compares saved values, and one with `load`
   * compares loaded values.
   *
   * @returns `false` if the row or the field doesn't exist.
   * @throws Error if the field isn't transformed, or can't be compared.
   *
   * @example
   * ```ts
   * const ok = await db.compare(["users", id], "password", input.password);
   * ```
   */
  compare: <const Key extends KrvAnyKey<Tables>>(
    key: Key,
    fieldName: KrvFieldAt<Tables, E, Key>,
    plain: unknown,
  ) => Promise<boolean>;
  /** Closes the database. */
  close: () => void;
}
type TablesOf<Db> =
  Db extends KrvDatabase<infer Tables, infer _E> ? Tables : never;
type ReadonlyLiterals<L> = L extends readonly string[] ? Readonly<L> : never;
/**
 * Row type of table, as read back. `Db` is the database's type, so custom
 * validators and transforms resolve; the table is named by its key's literal
 * parts, as in `insert` and `list`.
 *
 * @example
 * ```ts
 * export type Post = KrvRow<typeof db, ["posts"]>;
 * ```
 */
export type KrvRow<Db, Literals extends KrvAnyLiterals<TablesOf<Db>>> =
  Db extends KrvDatabase<infer Tables, infer E>
    ? KrvValueAtLiterals<Tables, E, ReadonlyLiterals<Literals>>
    : never;
/**
 * What `insert` accepts for a table: generated fields and timestamps may be
 * left out.
 *
 * @example
 * ```ts
 * export type NewPost = KrvInput<typeof db, ["posts"]>;
 * ```
 */
export type KrvInput<Db, Literals extends KrvAnyLiterals<TablesOf<Db>>> =
  Db extends KrvDatabase<infer Tables, infer E>
    ? KrvInputAtLiterals<Tables, E, ReadonlyLiterals<Literals>>
    : never;
/**
 * Secrets for the built-in transforms:
 * - `key`: the keys of `#` (HMAC) and `&` (AES-GCM) are derived from it.
 * - `pepper`: mixed into every `*` password before bcrypt.
 *
 * Losing them makes every stored `#`, `*` and `&` value useless: keep a copy
 * outside the database.
 */
export type KrvSecrets = {
  key: string;
  pepper: string;
};
/** The built-in transforms, as seen by the row types. */
export type KrvDefaultTransforms = {
  "#": {
    save: (value: unknown) => Promise<string>;
    deterministic: true;
  };
  "*": {
    save: (value: unknown) => Promise<string>;
    compare: (plain: unknown, stored: string) => Promise<boolean>;
  };
  "&": {
    save: (value: unknown) => Promise<string>;
    load: (stored: string) => Promise<unknown>;
  };
};
/** The default transforms, minus those replaced by `T`, plus `T`. */
export type KrvWithDefaultTransforms<T> = Omit<KrvDefaultTransforms, keyof T> &
  T;
type ValidatorMap<V, F> = {
  [K in keyof V]: readonly [
    V[K],
    K extends keyof F
      ? F[K] extends readonly [unknown, infer Fn]
        ? Fn
        : never
      : never,
  ];
};
type Env<V, F, T> = KrvEnv<ValidatorMap<V, F>, KrvWithDefaultTransforms<T>>;
/** What `defineKRV` takes: the schema part of `openKRV`'s options. */
export type KrvConfig<V, F, T, Tables extends readonly unknown[]> = {
  /**
   * Custom types: `name: [baseType, (value) => boolean]`, or with
   * arguments `"name(a, b)": [baseType, (value, { a, b }) => boolean]`.
   */
  validators?: KrvValidatorDefs<V> & F;
  /**
   * What a field name's transform character stores instead of the plain
   * value: `"*": { save, compare }`, `"&": { save, load }`,
   * `"#": { save, deterministic: true }`. `#` (HMAC-SHA256), `*` (peppered
   * bcrypt) and `&` (AES-256-GCM) are built in; declaring them here replaces
   * them.
   */
  transforms?: T & KrvTransforms;
  /**
   * The tables, each named by its key's literal parts (`["posts", "{id}"]`
   * is `posts`). Checked against `validators` once they are inferred.
   * Default none.
   */
  tables?: {
    [I in keyof Tables]: Tables[I] &
      KrvTable<readonly string[], KrvSchemaFor<ValidatorMap<V, F>>>;
  };
};
/**
 * A `defineKRV` result: its options as inferred, so `openKRV` infers them the
 * same way again when they're spread into it.
 */
export type KrvDefinedConfig<F, T, Tables> = {
  validators?: F;
  transforms?: T;
  tables?: Tables;
};
/** Types carried by a `defineKRV` result, read by `KrvDatabaseOf`. */
export type KrvConfigTypes<Tables extends KrvTables, E> = {
  readonly "~krv"?: {
    tables: Tables;
    env: E;
  };
};
/**
 * The database type of a `defineKRV` config, e.g. for migrations:
 * `KrvMigration<KrvDatabaseOf<typeof config>>`.
 */
export type KrvDatabaseOf<C> = C extends {
  readonly "~krv"?: {
    tables: infer Tables extends KrvTables;
    env: infer E;
  };
}
  ? KrvDatabase<Tables, E>
  : never;
/**
 * Declares tables, validators and transforms apart from `openKRV`, so their
 * database type can be named without opening it (`KrvDatabaseOf`). Useful
 * where `openKRV`'s own result can't be used, like in migrations, which it
 * imports. Pass it to `openKRV` spread: `openKRV({ ...config, path })`.
 *
 * @example
 * ```ts
 * // db/config.ts
 * export const config = defineKRV({ tables: [users, posts] });
 * export type Db = KrvDatabaseOf<typeof config>;
 *
 * // db/migrations/2026-09-24--001--names.ts
 * export default {
 *   url: import.meta.url,
 *   up: async (db) => { await db.insert(["users"], { name: "ana" }); }, // typed
 * } satisfies KrvMigration<Db>;
 * ```
 */
export declare const defineKRV: <
  const V extends Record<string, KrvSpec> = KrvNoValidators,
  F extends {
    [K in keyof V]: readonly [unknown, unknown];
  } = {
    [K in keyof V]: readonly [unknown, unknown];
  },
  const T extends KrvTransforms = KrvNoTransforms,
  const Tables extends readonly KrvTable[] = readonly [],
>(
  config: KrvConfig<V, F, T, Tables>,
) => KrvDefinedConfig<F, T, Tables> & KrvConfigTypes<Tables, Env<V, F, T>>;
/**
 * Opens a database.
 *
 * 1. Validators and transforms are registered, then every table is checked
 *    against them. Invalid schemas are compile errors, and throw
 *    `KrvSchemaError` at runtime.
 * 2. With a database file, `<path>.lock` is taken: only one process opens,
 *    migrates or checks at a time; others wait.
 * 3. Pending migrations run, by the date and number in their file name,
 *    after a backup of the file.
 * 4. Tables whose definition changed (all of them after a migration) have
 *    their rows checked and their indexes rebuilt. Any failure restores the
 *    backup and throws.
 *
 * @example
 * ```ts
 * const db = await openKRV({
 *   path: "./database",
 *   validators: {
 *     email: ["string", (v) => v.includes("@")],
 *   },
 *   tables: [
 *     table({
 *       key: ["users", "{userId}"],
 *       // "#" (SHA-256) and "*" (bcrypt) are built-in transforms.
 *       schema: { id: "{userId}", "email#": "email", "password*": "string" },
 *       indexes: { byEmail: { fields: ["email"], unique: true } },
 *     }),
 *   ],
 *   migrations: [import("./migrations/2026-09-01--001--users.ts")],
 * });
 * ```
 */
export declare const openKRV: <
  const V extends Record<string, KrvSpec> = KrvNoValidators,
  F extends {
    [K in keyof V]: readonly [unknown, unknown];
  } = {
    [K in keyof V]: readonly [unknown, unknown];
  },
  const T extends KrvTransforms = KrvNoTransforms,
  const Tables extends readonly KrvTable[] = readonly [],
>(options: {
  /** Database file, or `":memory:"`. Omit for Deno's default location. */
  path?: string;
  /**
   * Custom types: `name: [baseType, (value) => boolean]`, or with
   * arguments `"name(a, b)": [baseType, (value, { a, b }) => boolean]`.
   */
  validators?: KrvValidatorDefs<V> & F;
  /**
   * What a field name's transform character stores instead of the plain
   * value: `"*": { save, compare }`, `"&": { save, load }`,
   * `"#": { save, deterministic: true }`. `#` (HMAC-SHA256), `*` (peppered
   * bcrypt) and `&` (AES-256-GCM) are built in; declaring them here replaces
   * them.
   */
  transforms?: T & KrvTransforms;
  /**
   * The tables, each named by its key's literal parts (`["posts", "{id}"]`
   * is `posts`). Checked against `validators` once they are inferred.
   * Default none.
   */
  tables?: {
    [I in keyof Tables]: Tables[I] &
      KrvTable<readonly string[], KrvSchemaFor<ValidatorMap<V, F>>>;
  };
  /**
   * Migrations, as modules: `[import("./migrations/2026-09-24--001--users.ts")]`.
   * Each file's name (from `url: import.meta.url`) orders them: by date,
   * then number.
   */
  migrations?: KrvMigrationSource[];
  /** Migration lifecycle hooks, awaited. */
  events?: KrvEvents;
  /**
   * Key (`#`, `&`) and pepper (`*`) of the built-in transforms. By default
   * they're kept in the binary `<path>.secrets`, created on first open; pass
   * them when there's no database file (Deno's default location).
   */
  secrets?: KrvSecrets;
  /** Milliseconds before an untouched lock file is taken over. Default 30s. */
  lockTimeout?: number;
}) => Promise<KrvDatabase<Tables, Env<V, F, T>>>;
/**
 * Declares a table. Its schema is checked by `openKRV`, against its validators.
 *
 * @param definition
 *   - `key`: literal parts and `{placeholder}` parts, e.g. `["users", "{userId}"]`.
 *     Without placeholders the table is static: one value at exactly that key.
 *   - `schema`: the row's fields. See the README for the full syntax.
 *
 * @example
 * ```ts
 * table({
 *   key: ["posts", "{postId}"],
 *   schema: {
 *     id: "{postId}",
 *     authorId: "{users.userId}",
 *     title: "string",
 *     "tags[]": "string",
 *     status: ["|draft|", "|published|"],
 *   },
 * });
 * ```
 */
export declare const table: <
  const Key extends readonly string[],
  const Schema extends KrvSchemaDef,
  const Timestamps extends boolean = true,
  const Indexes extends Record<string, KrvIndex> = Record<never, never>,
>(definition: {
  key: Key;
  schema: Schema;
  /** Automatic `createdAt` / `updatedAt` fields. Default `true`. */
  timestamps?: Timestamps;
  /** Secondary indexes over top-level fields, by name. */
  indexes?: Indexes;
}) => NoInfer<KrvTable<Key, Schema, Timestamps, Indexes>>;
/** A table definition or validator is invalid. Thrown by `openKRV`. */
export declare class KrvSchemaError extends Error {
  constructor(message: string);
}
export type ParsedMigrationName = {
  /**
   * `YYYY-MM-DD--NNN`: what's recorded once applied, so renaming the name
   * part doesn't run it again.
   */
  id: string;
  /** `YYYY-MM-DD`. */
  date: string;
  /** The `NNN` part: the order within the day. */
  number: number;
  name?: string;
};
/** Splits a migration's file name, or returns `null` if it isn't one. */
export declare const parseMigrationName: (
  fileName: string,
) => ParsedMigrationName | null;
/**
 * The next migration file name (without extension): today's (local) date,
 * `number` or the next one for that date among `existing` file names, and
 * `name` as a slug, if any.
 *
 * @example
 * ```ts
 * nextMigrationName([], "First migration"); // "2026-09-24--001--first-migration"
 * nextMigrationName(["2026-09-24--001--first-migration.ts"]); // "2026-09-24--002"
 * ```
 */
export declare const nextMigrationName: (
  existing: Iterable<string>,
  name?: string,
  now?: Date,
  number?: number,
) => string;
export declare class KrvValidationError extends Error {
  readonly issues: string[];
  constructor(issues: string[]);
}
/**
 * A write lost to another one: a `check` failed, a key or unique value is
 * already taken, or concurrent writes kept winning.
 */
export declare class KrvConflictError extends Error {
  readonly key: KrvKey;
  constructor(key: KrvKey, message?: string);
}
/** A foreign key points at a missing row, or a delete is restricted by references. */
export declare class KrvReferenceError extends Error {
  constructor(message: string);
}
/** The row to update doesn't exist. */
export declare class KrvNotFoundError extends Error {
  readonly key: KrvKey;
  constructor(key: KrvKey);
}

export {};
