name: Build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [2.x.x]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --frozen-lockfile

      - name: run prettier checker
        run: yarn run prettier:check

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: run tests
        run: deno task test

      - name: check publish
        run: yarn run publish:check
